package org.apache.cordova.twiliovideo;

/**
 * Created by rpanadero on 13/9/18.
 * Further Developed by VOIDBLOCK TEAM
 */

public enum CallEvent { OPENED, CONNECTED, CONNECT_FAILURE, DISCONNECTED, DISCONNECTED_WITH_ERROR, PARTICIPANT_CONNECTED, 
    PARTICIPANT_DISCONNECTED, AUDIO_TRACK_ADDED, AUDIO_TRACK_REMOVED, VIDEO_TRACK_ADDED, VIDEO_TRACK_REMOVED, CLOSED, 
    WIDGET_MIN, WIDGET_MAX, WIDGET_SHOW, WIDGET_HIDE, SWITCHED_TO_FRONT_CAMERA, SWITCHED_TO_BACK_CAMERA, 
    MIC_ENABLED, MIC_DISABLED, MIC_MUTED, MIC_UNMUTED }
